dataStore_root: dataStore

data_ingestion:

  root_dir: dataStore/data_ingestion
  source_url: https://github.com/adyaan1989/datasetsforProjects/raw/main/IMDB_Datasetgit.zip
  local_data_file: dataStore/data_ingestion/data.zip
  unzip_dir: dataStore/data_ingestion


data_validation:
  root_dir: dataStore/data_validation
  unzip_data_dir: dataStore/data_ingestion/IMDB_Datasetgit.csv
  STATUS_FILE: dataStore/data_validation/status.txt
  

EDA_DataCleaner:
  root_dir: dataStore/EDA_DataCleaner
  data_path: dataStore/data_ingestion/IMDB_Datasetgit.csv
  

data_transformation:
  root_dir: dataStore/data_transformation
  clean_data_path: dataStore/EDA_DataCleaner/data.csv
  tokenizer_path: tokenizer.joblib
  
model_trainer:
  root_dir: dataStore/model_trainer
  X_train_data_path: dataStore/data_transformation/X_train.npy
  y_train_data_path: dataStore/data_transformation/y_train
  X_test_data_path: dataStore/data_transformation/X_text.npy
  y_test_data_path: dataStore/data_transformation/y_test
  saved_model_path: model.joblib


model_evaluation:
  root_dir: dataStore/model_evaluation # this would create the path inside datastore to save the evaluation
  X_test_data_path: dataStore/data_transformation/X_text.npy
  y_test_data_path: dataStore/data_transformation/y_test
  model_path: dataStore/model_trainer/model.joblib # this pick the model from datastore

model_prediction:
  root_dir: dataStore/model_prediction # this would create the path inside datastore to save the evaluation
  tokens_path: dataStore/data_transformation/tokenizer.joblib
  final_model_path: dataStore/model_trainer/model.joblib # this pick the model from datastore
  save_model_performance: dataStore/model_prediction
