dataStore_root: dataStore

data_ingestion:

  root_dir: dataStore/data_ingestion
  source_url: https://github.com/adyaan1989/datasetsforProjects/raw/main/IMDB_datasets.zip
  local_data_file: dataStore/data_ingestion/data.zip
  unzip_dir: dataStore/data_ingestion



data_validation:

  root_dir: dataStore/data_validation
  STATUS_FILE: dataStore/data_validation/status.txt
  ALL_REQUIRED_FILES: ["train","text","validation"]


# Data_Transformation:
#   root_dir: dataStore/Data_Transformation
#   data_path: dataStore/data_ingestion/IMDB_DataSets


# model_trainer:
#   root_dir: dataStore/model_trainer
#   data_path: dataStore/data_transformation/IMDB_DataSets

